server:
  port: 8091

spring:
  config:
    import:
      - configserver:http://localhost:8763
  application:
    name: school-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/students
    username: postgres
    password: Saidboudad+
  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

application:
  config:
    students-url: http://localhost:8090/api/v1/students

management:
  endpoints:
    web:
      exposure:
        include: "*"